version: '3.3'
services:
  alist:
    restart: always
    volumes:
      - '/data/alist:/opt/alist/data'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    container_name: alist
    image: 'xhofe/alist:latest'
    privileged: true
    network_mode: host
    # ports:
    #   - '5244:5244'

