# Your Wi-Fi SSID and password
wifi_ssid: "qwerty"
wifi_password: "wodemima@123456"

ap_wifi_password: "12345678"

api_password: "xvlfQiq46elBCJ4nykDlV/bzNwHET9gsT7dTxpgQZlQ="
api_encryption_key: "xvlfQiq46elBCJ4nykDlV/bzNwHET9gsT7dTxpgQZlQ="

ota_password: "6f0f4acea72c0081925e70dcea333f90"


# ota_password: "XIYIZI130816"

web_password: "admin"
